name: food_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  flutter_lints: ^3.0.0
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.24.2
  image_picker: ^1.0.7
  random_string: ^2.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # example:
  fonts:
    - family: Poppins
      fonts:
         - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
