// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQPcy80NUHwiYt3MKtQKk-7iZJqW58mE',
    appId: '1:119519382022:web:87a687037b565108695187',
    messagingSenderId: '119519382022',
    projectId: 'food-350ec',
    authDomain: 'food-350ec.firebaseapp.com',
    storageBucket: 'food-350ec.appspot.com',
    measurementId: 'G-3G0JJZ2QMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBypLZ5JzytolyDwqEXLWM5jmbjfC3RuVw',
    appId: '1:119519382022:android:4793cfc1f14f816d695187',
    messagingSenderId: '119519382022',
    projectId: 'food-350ec',
    storageBucket: 'food-350ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC18vjfLUlmfpCqsBFY2RvNbP_-4pEgIrk',
    appId: '1:119519382022:ios:9186dc1f490c6783695187',
    messagingSenderId: '119519382022',
    projectId: 'food-350ec',
    storageBucket: 'food-350ec.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC18vjfLUlmfpCqsBFY2RvNbP_-4pEgIrk',
    appId: '1:119519382022:ios:c3111e61a6cfed8a695187',
    messagingSenderId: '119519382022',
    projectId: 'food-350ec',
    storageBucket: 'food-350ec.appspot.com',
    iosBundleId: 'com.example.foodApp.RunnerTests',
  );
}
